app.database.mode=development
app.database.development.relative-dir=../../idorendmaker-desktop

logging.level.hu.szabolcst.idorendmaker=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.properties.hibernate.format_sql=true
