Args = --add-modules=java.desktop \
       --enable-all-security-services \
       --initialize-at-run-time=java.awt \
       --initialize-at-run-time=javax.swing \
       --initialize-at-run-time=sun.awt \
       --initialize-at-run-time=sun.java2d \
       --initialize-at-run-time=java.awt.image.ColorModel \
       --initialize-at-run-time=java.awt.image.Raster \
       --initialize-at-run-time=java.awt.Toolkit \
       --initialize-at-run-time=java.awt.Font \
       --initialize-at-run-time=java.awt.font.FontRenderContext \
       --initialize-at-run-time=org.apache.pdfbox.pdmodel.PDDocument \
       --initialize-at-run-time=javax.imageio \
       --initialize-at-build-time=org.apache.pdfbox.text \
       --initialize-at-build-time=org.apache.pdfbox.io \
       --initialize-at-build-time=org.apache.commons.logging.LogAdapter$Slf4jLocationAwareLog \
       --initialize-at-build-time=org.apache.commons.logging.LogFactory \
       --initialize-at-build-time=org.slf4j \
       --initialize-at-build-time=ch.qos.logback.classic.Logger \
       --initialize-at-build-time=ch.qos.logback.classic.Level \
       --initialize-at-build-time=ch.qos.logback.classic.spi \
       --initialize-at-build-time=ch.qos.logback.core \
       --initialize-at-build-time=org.apache.catalina \
       --initialize-at-build-time=org.apache.coyote \
       --initialize-at-build-time=org.apache.tomcat \
       --initialize-at-build-time=org.apache.juli.logging.DirectJDKLog \
       --initialize-at-build-time=org.apache.juli.logging \
       --initialize-at-build-time=org.apache.juli \
       --initialize-at-build-time=org.springframework.core \
       --initialize-at-build-time=org.springframework.util \
       --initialize-at-build-time=org.springframework.beans \
       --initialize-at-build-time=org.springframework.context \
       --initialize-at-build-time=com.fasterxml.jackson \
       --initialize-at-build-time=com.fasterxml.jackson.databind \
       --initialize-at-build-time=com.fasterxml.jackson.core \
       --initialize-at-build-time=ch.qos.logback.classic.LoggerContext \
       --enable-https \
       --enable-url-protocols=http,https,jar \
       --enable-native-access=ALL-UNNAMED

Main-Class= hu.szabolcst.idorendmaker.IdorendMakerPdfProcessorApplication
