spring.application.name=idorendmaker-pdfprocessor
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.aot.enabled=true
spring.aot.repositories.enabled=true
spring.banner.location=classpath:banner.txt
